import { chemState } from '../state.js';

// ── DATA ───────────────────────────────────────
const CHEMICALS = [
  { id:'anticloro', cat:'Acondicionadores', name:'Acondicionador / Anticloro', icon:'💧', brand:'Seachem Prime, API Stress Coat, genérico', use:'Neutraliza cloro y cloraminas del agua de la llave antes de añadirla al acuario. Indispensable en cada cambio de agua.', cases:['Cambios parciales de agua','Llenado de acuario nuevo','Agua de la llave con cloro o cloraminas'], warnings:['No omitir aunque el agua "huela bien" — el cloro daña branquias aunque sea imperceptible','Seachem Prime también neutraliza amoniaco temporalmente; no confundir con ciclar el acuario','Sobredosis moderada (2–3×) es generalmente segura, pero no exceder sin necesidad'], compat:{ fish:true, plants:true, shrimp:true, snails:true } },
  { id:'estabilizador_ph', cat:'Acondicionadores', name:'Estabilizador de pH', icon:'⚗️', brand:'Seachem Neutral Regulator, API pH Down/Up, genérico', use:'Sube o baja el pH del agua hasta un valor objetivo y lo mantiene estable.', cases:['Agua con pH inadecuado para las especies','pH inestable con caídas nocturnas','Preparar agua para camarones Caridina'], warnings:['Cambios bruscos de pH son más dañinos que un pH "incorrecto" estable — ajustar gradualmente','No mezclar pH Up y pH Down en el mismo recipiente','Los tampones (buffers) son más seguros que los ajustadores directos para uso regular','Inútil si el KH es muy bajo — estabilizar KH primero'], compat:{ fish:true, plants:true, shrimp:{ ok:false, reason:'Los cambios de pH afectan el proceso de muda; los camarones son muy sensibles a variaciones' }, snails:{ ok:false, reason:'Los caracoles necesitan pH estable; los ajustadores bruscos dañan su concha y metabolismo' } } },
  { id:'estabilizador_kh', cat:'Acondicionadores', name:'Estabilizador de KH / Buffer', icon:'⚗️', brand:'Seachem Alkaline Buffer, API KH booster, genérico', use:'Eleva y estabiliza la dureza de carbonatos (KH), previniendo caídas de pH.', cases:['KH menor a 3–4 dKH (riesgo de pH crash)','Acuarios plantados con CO₂ inyectado','Agua de ósmosis o lluvia sin mineralizar'], warnings:['KH alto dificulta bajar el pH — no usar en acuarios de camarones Caridina que requieren pH 6.0–6.5','Verificar KH después de cada dosis; no sobredosificar','No confundir con GH (dureza general) — son parámetros distintos'], compat:{ fish:true, plants:true, snails:true, shrimp:{ ok:false, reason:'Los camarones Caridina necesitan KH muy bajo (0–2); elevar el KH impide su reproducción y puede matarlos' } } },
  { id:'azul_metileno', cat:'Medicamentos', name:'Azul de Metileno', icon:'🔵', brand:'Genérico / API', use:'Antifúngico y antiséptico de amplio espectro. Muy usado para tratar huevos infectados, hongos superficiales y como profiláctico en cuarentena.', cases:['Hongos en huevos durante la incubación','Infecciones fúngicas superficiales leves','Baños profilácticos en cuarentena','Tratamiento de Ich en estadios iniciales'], warnings:['Tiñe todo de azul intenso — silicón, decoración y plantas absorben el tinte permanentemente','Destruye bacterias benéficas del filtro — no tratar en el acuario principal si es posible','Usar guantes — tiñe piel y superficies'], compat:{ fish:true, plants:{ ok:false, reason:'Destruye la clorofila e inhibe la fotosíntesis; mata las plantas aunque sea en dosis bajas' }, shrimp:{ ok:false, reason:'Tóxico para invertebrados; afecta su sistema respiratorio y puede matarlos rápidamente' }, snails:{ ok:false, reason:'Tóxico para moluscos; daña sus tejidos blandos y sistema nervioso' } } },
  { id:'sal_acuario', cat:'Medicamentos', name:'Sal de Acuario', icon:'🧂', brand:'API Aquarium Salt, genérico (sal sin yodo)', use:'Reduce el estrés osmótico, estimula la producción de moco protector y ayuda en recuperación de enfermedades leves.', cases:['Recuperación post-enfermedad','Estrés por transporte','Tratamiento coadyuvante de Ich','Peces debilitados o con heridas'], warnings:['NO usar con peces de agua muy blanda (Discus, Altum, Scalare) — sensibles a la salinidad','No es sustituto de medicamentos específicos en infecciones graves','Usar sal sin yodo ni anti-apelmazante'], compat:{ fish:true, plants:{ ok:false, reason:'La sal extrae agua de las células vegetales por ósmosis, deshidratando y matando las plantas' }, shrimp:{ ok:false, reason:'Incluso dosis bajas alteran el equilibrio osmótico de los camarones, causando muerte en horas' }, snails:{ ok:false, reason:'La sal deshidrata los tejidos blandos del caracol; concentraciones pequeñas pueden ser letales' } } },
  { id:'metronidazol', cat:'Medicamentos', name:'Metronidazol', icon:'💊', brand:'Seachem Metronidazole, API General Cure', use:'Antiprotozoario y antibacteriano anaeróbico. Tratamiento de elección para enfermedades internas como Hexamita.', cases:['Enfermedad del hoyo en la cabeza (HLLE)','Hexamita / parásitos intestinales','Heces blancas o mucosas','Abdomen hinchado por parásitos internos'], warnings:['Solo eficaz contra protozoarios y anaerobios — no sirve contra Ich ni bacterias aeróbicas','Tratar vía alimento (mezclado en comida) es más efectivo que en el agua','Retirar carbón activo antes del tratamiento — lo absorbe y neutraliza'], compat:{ fish:true, plants:true, shrimp:true, snails:true } },
  { id:'malachite_green', cat:'Medicamentos', name:'Verde de Malaquita', icon:'🟢', brand:'Genérico, Kordon Rid-Ich', use:'Antiparasitario y antifúngico potente. Muy efectivo contra Ich, terciopelo y hongos externos.', cases:['Ich / Punto blanco','Terciopelo / Oodinium','Hongos externos severos','Saprolegnia en peces adultos'], warnings:['Potencialmente carcinógeno — usar guantes y evitar contacto con piel y ojos','Tóxico para peces sin escamas (Corydoras, plecos, bagres) — reducir dosis a la mitad','No usar en acuarios con luz intensa — se degrada rápido y pierde eficacia','Retirar carbón activo del filtro'], compat:{ fish:true, plants:{ ok:false, reason:'Inhibe la fotosíntesis y es fitotóxico; mata plantas acuáticas incluso en dosis terapéuticas' }, shrimp:{ ok:false, reason:'Letal para todos los invertebrados; afecta sus enzimas respiratorias de forma irreversible' }, snails:{ ok:false, reason:'Tóxico para moluscos; penetra sus tejidos blandos y causa muerte rápida' } } },
  { id:'formalina', cat:'Medicamentos', name:'Formalina', icon:'⚠️', brand:'Genérico (solución 37–40% formaldehído)', use:'Antiparasitario de uso externo muy potente. Elimina ectoparásitos como monogeneos, tricodina y costia.', cases:['Parásitos branquiales (monogeneos, tricodina)','Costia / Ichthyobodo','Branquiomicosis','Infestaciones externas severas resistentes a otros tratamientos'], warnings:['⚠️ TÓXICO — usar solo con ventilación adecuada, guantes y protección ocular','Dosis incorrecta puede matar peces rápidamente — pesar y calcular con precisión','No usar en agua con temperatura mayor a 27°C — aumenta toxicidad','Reduce el oxígeno disuelto — airear intensamente durante el tratamiento','Solo para usuarios con experiencia — considerar alternativas más seguras primero'], compat:{ fish:true, plants:{ ok:false, reason:'El formaldehído es un fijador celular; destruye los tejidos vegetales de inmediato' }, shrimp:{ ok:false, reason:'Extremadamente tóxico para crustáceos; concentraciones mínimas causan muerte instantánea' }, snails:{ ok:false, reason:'Letal para moluscos; el formaldehído desnaturaliza sus proteínas celulares' } } },
  { id:'kanamicina', cat:'Medicamentos', name:'Kanamicina / Antibióticos', icon:'💊', brand:'Seachem KanaPlex, API Furan-2, Thomas Labs', use:'Antibióticos de amplio espectro para infecciones bacterianas graves. Tratamiento de bacteriosis externas e internas, úlceras y dropsy.', cases:['Dropsy / hidropesía (escamas erizadas)','Úlceras o llagas profundas','Podredumbre de aletas severa con tejido necrótico','Infección bacteriana interna confirmada'], warnings:['Usar solo cuando sea necesario — el uso excesivo genera resistencia bacteriana','Destruye completamente las bacterias del filtro biológico — monitorear amoniaco','Completar el ciclo completo aunque el pez mejore antes','Retirar carbón activo del filtro durante el tratamiento'], compat:{ fish:true, plants:true, shrimp:{ ok:false, reason:'Los antibióticos alteran la microbiota intestinal de los camarones y pueden ser tóxicos directamente' }, snails:{ ok:false, reason:'Algunos antibióticos dañan el sistema digestivo de los moluscos y su microbioma' } } },
  { id:'fertilizante_liquido', cat:'Fertilizantes', name:'Fertilizante Líquido (macro y micro)', icon:'🌿', brand:'Seachem Flourish, API Leaf Zone, Tropica Premium', use:'Aporta micronutrientes y/o macronutrientes directamente a la columna de agua. Esencial en planted tanks con sustrato inerte.', cases:['Plantas con hojas amarillas (deficiencia de hierro)','Crecimiento lento o detenido','Planted tank con sustrato inerte','Suplemento a sustrato nutritivo maduro'], warnings:['El exceso de nutrientes favorece el crecimiento de algas — dosificar con criterio','Seachem Flourish Comprehensive no contiene nitrógeno ni fósforo — agregar por separado si necesario','Verificar deficiencias específicas antes de elegir el fertilizante'], compat:{ fish:true, plants:true, shrimp:true, snails:true } },
  { id:'pastillas_raiz', cat:'Fertilizantes', name:'Pastillas Fertilizantes de Raíz', icon:'🌱', brand:'Seachem Flourish Tabs, API Root Tabs, Tropica', use:'Fertilizante sólido que se entierra en el sustrato cerca de las raíces. Libera nutrientes de forma lenta y localizada.', cases:['Espadas amazónicas, Criptocorynes y otras plantas de raíz','Sustrato inerte sin capacidad nutritiva','Plantas con crecimiento deficiente a pesar de fertilización líquida'], warnings:['Enterrar profundo para evitar que los nutrientes pasen directamente al agua y causen algas','Renovar cada 3–6 meses según el fabricante','Las plantas flotantes o de columna no se benefician de este tipo de fertilizante'], compat:{ fish:true, plants:true, shrimp:true, snails:true } },
  { id:'hierro', cat:'Fertilizantes', name:'Hierro Quelado (Fe)', icon:'🟤', brand:'Seachem Flourish Iron, Estimula Fe, genérico', use:'Suplemento específico de hierro en forma quelada. Corrige deficiencias visibles como clorosis.', cases:['Hojas nuevas amarillas con venas visiblemente verdes (clorosis férrica)','Plantas rojas que pierden coloración','Planted tanks de alta demanda con CO₂'], warnings:['El hierro no quelado precipita rápidamente y es inútil','Exceso de hierro puede favorecer proliferación de algas — no sobredosificar','La deficiencia de hierro a veces indica pH demasiado alto que impide la absorción'], compat:{ fish:true, plants:true, shrimp:true, snails:true } },
  { id:'co2_liquido', cat:'Fertilizantes', name:'CO₂ Líquido (Glutaraldehído)', icon:'🌫️', brand:'Seachem Excel, Tropica Easy Carbo, Colombo Ferts', use:'Fuente de carbono líquida como alternativa al CO₂ gaseoso. También actúa como algicida suave.', cases:['Planted tanks sin sistema de CO₂ gaseoso','Control de algas negras (BBA)','Control de algas filamentosas verdes','Suplemento de carbono en épocas de alta demanda'], warnings:['⚠️ TÓXICO para Vallisneria y algunas Egeria — puede matarlas en una sola dosis estándar','Es un desinfectante (glutaraldehído) — puede afectar bacterias del filtro en sobredosis','Aplicar directamente sobre las algas negras con jeringa para mayor efectividad'], compat:{ fish:true, snails:true, plants:{ ok:false, reason:'El glutaraldehído es tóxico para Vallisneria y algunas Egeria incluso en dosis normales' }, shrimp:{ ok:false, reason:'El glutaraldehído es un biocida; en dosis altas o acumuladas puede matar camarones' } } },
  { id:'algicida', cat:'Control de Algas', name:'Algicida Químico', icon:'🟡', brand:'API Algaefix, Tetra AlguMin, genérico', use:'Elimina algas existentes y previene su proliferación. Útil como medida temporal.', cases:['Explosión de algas verdes en el agua (agua verde)','Algas en superficie y vidrios difíciles de controlar','Control temporal mientras se corrige el desequilibrio'], warnings:['Trata el síntoma, no la causa — sin corrección del desequilibrio las algas volverán','Puede reducir el oxígeno al matar algas masivamente — airear bien','No usar en sistemas con invertebrados bajo ninguna circunstancia'], compat:{ fish:true, plants:{ ok:false, reason:'Los algicidas no distinguen entre algas y plantas; dañan o matan plantas acuáticas' }, shrimp:{ ok:false, reason:'⚠️ LETAL — los algicidas matan camarones incluso en dosis mínimas; nunca usar juntos' }, snails:{ ok:false, reason:'⚠️ LETAL — los algicidas son tóxicos para todos los moluscos sin excepción' } } },
  { id:'peroxido', cat:'Control de Algas', name:'Peróxido de Hidrógeno (H₂O₂)', icon:'💥', brand:'Farmacia (agua oxigenada 3–12%)', use:'Oxidante potente para eliminar algas específicas por aplicación directa. Muy eficaz contra algas negras y cianobacterias.', cases:['Algas negras (BBA) en plantas y decoración','Cianobacterias (algas azul-verdosas)','Desinfección de plantas nuevas antes de introducirlas','Desinfección de decoración y utensilios'], warnings:['Se degrada en agua y oxígeno — relativamente seguro si se aplica con cuidado y buena aireación','Aplicación directa es muy eficaz; dosis al agua completa puede dañar peces y bacterias','Usar solución máx. 3% en acuario; concentraciones mayores solo fuera del agua'], compat:{ fish:true, plants:true, shrimp:{ ok:false, reason:'Oxidante potente que daña las branquias y tejidos de los camarones; retirar antes del tratamiento' }, snails:{ ok:false, reason:'El H₂O₂ daña los tejidos blandos y la concha de los caracoles; retirar antes de aplicar' } } },
  { id:'carbon_activo', cat:'Calidad del Agua', name:'Carbón Activo', icon:'⬛', brand:'Seachem Matrix Carbon, Fluval Carbon, genérico', use:'Adsorbente que elimina químicos, medicamentos, colorantes, olores y algunos metales pesados del agua.', cases:['Después de un tratamiento con medicamentos para eliminar residuos','Agua amarillenta por taninos (madera, hojas)','Eliminar olores del agua','Acuarios de exhibición donde se prioriza la transparencia'], warnings:['Se satura en 2–4 semanas y deja de funcionar — reemplazar periódicamente','Elimina medicamentos activos — retirar siempre durante los tratamientos','El carbón gastado puede liberar lo que adsorbió — no reutilizar'], compat:{ fish:true, shrimp:true, snails:true, plants:{ ok:false, reason:'Absorbe fertilizantes y micronutrientes del agua, privando a las plantas de su nutrición' } } },
  { id:'zeolita', cat:'Calidad del Agua', name:'Zeolita', icon:'🪨', brand:'Seachem Purigen, API Ammonia Chips, genérico', use:'Mineral poroso que adsorbe amoniaco del agua. Útil en emergencias de amoniaco o acuarios sin ciclar.', cases:['Picos de amoniaco en acuarios nuevos sin ciclar','Emergencias con peces enfermos o superpoblación','Acuarios de cuarentena o transporte'], warnings:['Solo funciona en agua dulce — pierde eficacia en agua salada o con sal','Se satura rápidamente en acuarios con carga alta de peces','No reemplaza el ciclo biológico del filtro — es una solución temporal'], compat:{ fish:true, plants:true, shrimp:true, snails:true } },
  { id:'clarificante', cat:'Calidad del Agua', name:'Clarificante de Agua', icon:'🔮', brand:'Seachem Clarity, API Accu-Clear, genérico', use:'Aglutina partículas finas en suspensión formando grumos que el filtro puede capturar.', cases:['Agua turbia por polvo de sustrato nuevo','Turbidez bacteriana en acuario nuevo','Agua nublada de causa no identificada','Previo a fotografiar o exhibir el acuario'], warnings:['Trata el síntoma — identificar y corregir la causa de la turbidez','No usar en exceso; puede aglutinar partículas útiles y obstruir el filtro','Si la turbidez es verde (algas) usar algicida, no clarificante'], compat:{ fish:true, plants:true, shrimp:true, snails:true } },
  { id:'osmosis_remineralizador', cat:'Calidad del Agua', name:'Remineralizador (agua de ósmosis)', icon:'💎', brand:'Seachem Equilibrium, Salty Shrimp GH+, genérico', use:'Añade minerales al agua desmineralizada de ósmosis inversa para hacerla apta para los peces.', cases:['Agua de ósmosis inversa pura (GH y KH = 0)','Preparar agua específica para camarones Caridina','Control preciso de parámetros en especies sensibles','Agua de lluvia o muy blanda'], warnings:['Solo para agua de ósmosis o muy blanda — añadir a agua dura puede elevar parámetros peligrosamente','Equilibrium no contiene sodio — ideal para agua dulce pero no sustituye KH buffer','Calcular siempre la cantidad necesaria con base en el volumen real del acuario'], compat:{ fish:true, plants:true, shrimp:true, snails:true } },
  { id:'bacterias_inicio', cat:'Bacterias Benéficas', name:'Bacterias de Arranque / Cicladoras', icon:'🦠', brand:'Seachem Stability, API Quick Start, Tetra SafeStart', use:'Introducen colonias de bacterias nitrificantes para acelerar el ciclo del nitrógeno en acuarios nuevos.', cases:['Acuario nuevo sin ciclar','Después de tratamiento con antibióticos que destruyó el filtro','Tras limpieza excesiva del filtro','Reconfiguración total del acuario'], warnings:['No añadir peces inmediatamente — dar tiempo a que las bacterias se establezcan (1–2 semanas mínimo)','Caducan — verificar fecha antes de usar','No usar junto con antibióticos o medicamentos que maten bacterias','No reemplazan el monitoreo de parámetros — seguir midiendo amoniaco y nitrito'], compat:{ fish:true, plants:true, shrimp:true, snails:true } },
  { id:'probioticos', cat:'Bacterias Benéficas', name:'Probióticos / Bacterias Degradadoras', icon:'🦠', brand:'Seachem Pristine, Microbe-Lift, genérico', use:'Bacterias heterótrofas que degradan materia orgánica reduciendo carga orgánica y mejorando la calidad del agua.', cases:['Acuarios con exceso de materia orgánica','Fondo con acumulación de detritos','Reducción de nitratos en acuarios establecidos','Soporte a filtraciones biológicas insuficientes'], warnings:['Complemento, no sustituto de un filtro adecuado y mantenimiento regular','Pueden reducir temporalmente el oxígeno al proliferar — airear bien','Abrir y usar rápido — el producto se degrada al exponerse al aire'], compat:{ fish:true, plants:true, shrimp:true, snails:true } },
];

const CHEM_CATS = ['Acondicionadores', 'Medicamentos', 'Fertilizantes', 'Control de Algas', 'Calidad del Agua', 'Bacterias Benéficas'];
const CHEM_CAT_META = {
  'Acondicionadores':    { icon: '💧', color: '#1565c0', desc: 'Preparan y estabilizan el agua' },
  'Medicamentos':        { icon: '💊', color: '#b71c1c', desc: 'Tratan enfermedades y parásitos' },
  'Fertilizantes':       { icon: '🌿', color: '#2e7d32', desc: 'Nutrición para plantas acuáticas' },
  'Control de Algas':    { icon: '🟡', color: '#f57f17', desc: 'Eliminan o previenen algas' },
  'Calidad del Agua':    { icon: '🔮', color: '#4a148c', desc: 'Filtración y purificación' },
  'Bacterias Benéficas': { icon: '🦠', color: '#00695c', desc: 'Ciclo del nitrógeno y limpieza' },
};


// ── RENDER ─────────────────────────────────────
export function renderChem() {
  const el = document.getElementById('tab-chem');
  if (!el) return;

  const compatOk = v => v === true || v?.ok === true;

  let html = `<div class="chem-page"><div class="chem-header"><h2 class="chem-title">🧪 Química del Acuario</h2><p class="chem-subtitle">Guía de productos y sustancias para agua dulce</p></div><div class="chem-cats">`;

  CHEM_CATS.forEach(cat => {
    const meta  = CHEM_CAT_META[cat];
    const items = CHEMICALS.filter(c => c.cat === cat);
    const isOpen = chemState.openCat === cat;
    html += `<div class="chem-cat-block"><div class="chem-cat-header" onclick="toggleChemCat('${cat}')" style="--ccat:${meta.color}"><span class="chem-cat-icon">${meta.icon}</span><div class="chem-cat-info"><div class="chem-cat-name">${cat}</div><div class="chem-cat-desc">${meta.desc} · ${items.length} productos</div></div><span class="chem-cat-chevron">${isOpen ? '▴' : '▾'}</span></div><div class="chem-cat-items${isOpen ? ' open' : ''}">`;

    items.forEach(item => {
      const isItemOpen = chemState.openItem === item.id;
      const compatIcons = [
        `<span class="compat-badge ${compatOk(item.compat.fish)   ? 'ok' : 'no'}" title="Peces">🐟</span>`,
        `<span class="compat-badge ${compatOk(item.compat.plants) ? 'ok' : 'no'}" title="Plantas">🌿</span>`,
        `<span class="compat-badge ${compatOk(item.compat.shrimp) ? 'ok' : 'no'}" title="Camarones">🦐</span>`,
        `<span class="compat-badge ${compatOk(item.compat.snails) ? 'ok' : 'no'}" title="Caracoles">🐌</span>`,
      ].join('');

      html += `<div class="chem-item${isItemOpen ? ' open' : ''}" onclick="toggleChemItem('${item.id}')"><div class="chem-item-row"><span class="chem-item-icon">⚫</span><div class="chem-item-main"><div class="chem-item-name">${item.name}</div></div><div class="chem-compat-row">${compatIcons}</div><span class="chem-chevron">${isItemOpen ? '▴' : '▾'}</span></div><div class="chem-item-detail${isItemOpen ? ' open' : ''}"><div class="chem-brand-row"><span class="chem-brand-label">Marcas</span><span class="chem-brand-value">${item.brand}</span></div><div class="chem-section"><div class="chem-section-title">¿Para qué sirve?</div><p class="chem-use-text">${item.use}</p></div><div class="chem-section"><div class="chem-section-title">¿Cuándo usarlo?</div><ul class="chem-cases">${item.cases.map(c => `<li>${c}</li>`).join('')}</ul></div><div class="chem-section warn-section"><div class="chem-section-title">⚠️ Precauciones</div><ul class="chem-warnings">${item.warnings.map(w => `<li>${w}</li>`).join('')}</ul></div><div class="chem-section"><div class="chem-section-title">Compatibilidad</div><div class="chem-compat-grid">${buildCompatRow('🐟','Peces',item.compat.fish)}${buildCompatRow('🌿','Plantas',item.compat.plants)}${buildCompatRow('🦐','Camarones',item.compat.shrimp)}${buildCompatRow('🐌','Caracoles',item.compat.snails)}</div></div></div></div>`;
    });

    html += `</div></div>`;
  });

  html += `</div></div>`;
  el.innerHTML = html;
}

function buildCompatRow(icon, label, val) {
  const ok     = val === true || val?.ok === true;
  const reason = (!ok && typeof val === 'object') ? val.reason : null;
  return `<div class="compat-detail-row ${ok ? 'ok' : 'no'}"><span class="compat-dr-icon">${icon}</span><div class="compat-dr-body"><span class="compat-dr-status">${ok ? '✅ Compatible' : '❌ No usar'}</span>${reason ? `<span class="compat-dr-reason">${reason}</span>` : ''}</div></div>`;
}

export function toggleChemCat(cat) {
  chemState.openCat  = chemState.openCat === cat ? null : cat;
  chemState.openItem = null;
  renderChem();
}

export function toggleChemItem(id) {
  chemState.openItem = chemState.openItem === id ? null : id;
  renderChem();
}
